services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - 3306:3306
volumes:
  db-data:
